### ISSUE TITLE
A1-Trippy Grid

### ISSUE THREAD

**Issue by NidheeshJain** [NidheeshJain/frontend-101#1]

**Comment by jshreyans** [comment]
Please deploy this to Github Pages. That way, it's easier for us to test out. And this applies to all the other tasks as well, except I think B5.

**Comment by NidheeshJain** [comment]
Github Page edited

**Comment by jshreyans** [comment]
Looks great :100: 
One small thing, there should be a minimum width for the boxes. So if the user tries to reduce width beyond this minimum, the boxes should stop translating and simply occupy the entire width.

**Comment by NidheeshJain** [comment]
Translation beyond some small width stopped.
